name: 更新JSON文件

on: push

permissions:
  contents: write

jobs:
  job1:
    name: 更新JSON文件
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库
        uses: actions/checkout@v4

      - name: 运行脚本1
        run: python fmtCvrs.py
      - name: 运行脚本2
        run: |
         pip initall httpx
         python getStatus.py

      - name: 提交更改
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}          
          git add .
          git commit -m ":sparkles: update JSON file"
      - name: PUSH
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GH_TOKEN}}
      - name: 刷新缓存
        run: |
          curl -X GET https://jsd.seeku.site/yzyyz1387/hamSoftware/res-web.json

